### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by MinnaHajimehaTamago** [MinnaHajimehaTamago/furima-323343#10]
# URL
https://furima-323343.herokuapp.com/#10 
# Basic認証のIDとパスワード
ID：admin
パスワード：2222
# 出品者用アカウント
メールアドレス：seller@com
パスワード：seller2020
# 購入者用アカウント
メールアドレス：buyer@com
パスワード：buyer2020
# 購入用カード
カード番号：4242424242424242
期限：3/24
セキュリティコード：123

**Comment by techcamp-N** [comment]
@MinnaHajimehaTamago さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**Comment by MinnaHajimehaTamago** [comment]
ありがとうございます！
